"""DBCache model

Revision ID: 77b18bf90aa4
Revises: 931ae6485853
Create Date: 2026-02-17 18:40:14.124517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database import EncryptedJSONType


# revision identifiers, used by Alembic.
revision: str = '77b18bf90aa4'
down_revision: Union[str, Sequence[str], None] = '931ae6485853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_table',
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('validity', sa.Integer(), nullable=False),
    sa.Column('data', EncryptedJSONType(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache_table')
    # ### end Alembic commands ###
