"""add managed object field

Revision ID: 931ae6485853
Revises: d9411d99dc0a
Create Date: 2026-02-05 12:42:40.635935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.database import EncryptedJSONType

# revision identifiers, used by Alembic.
revision: str = '931ae6485853'
down_revision: Union[str, Sequence[str], None] = 'd9411d99dc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manageddbmodels')
    op.add_column('authenticator_table', sa.Column('data', EncryptedJSONType(), nullable=True))
    op.alter_column('authenticator_table', 'mfa',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('mfa_table', sa.Column('data', EncryptedJSONType(), nullable=True))
    op.add_column('users_group_table', sa.Column('auth_uuid', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_group_table', 'auth_uuid')
    op.drop_column('mfa_table', 'data')
    op.alter_column('authenticator_table', 'mfa',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('authenticator_table', 'data')
    op.create_table('manageddbmodels',
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('manageddbmodels_pkey'))
    )
    # ### end Alembic commands ###
