"""uuid as pk for user

Revision ID: a0d9829f97e5
Revises: a3bce89363e0
Create Date: 2025-12-02 14:17:53.920822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d9829f97e5'
down_revision: Union[str, Sequence[str], None] = 'a3bce89363e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
