"""data field to user for encrypted data (emails for ex)

Revision ID: b272bd285931
Revises: a0d9829f97e5
Create Date: 2025-12-02 16:54:33.364794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b272bd285931'
down_revision: Union[str, Sequence[str], None] = 'a0d9829f97e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data', sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data')
    # ### end Alembic commands ###
