"""initial with authentication tables

Revision ID: d9411d99dc0a
Revises: 
Create Date: 2025-12-18 17:33:38.313323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9411d99dc0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_table',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mfa_type', sa.Enum('TOTP', name='mfatype'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'HIDDEN', 'DISABLED', name='availabilitystate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_table',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('real_name', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='userstate'), nullable=False),
    sa.Column('role', sa.Enum('DEMO', 'PLAIN_USER', 'STAFF_ADMIN', 'LICENSE_ADMIN', name='userrole'), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users_group_table',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('authenticator_table',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('auth_type', sa.Enum('IP', 'DB', 'RADIUS', 'LDAP', name='authtype'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'HIDDEN', 'DISABLED', name='availabilitystate'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('mfa', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mfa'], ['mfa_table.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users_groups',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('group_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['users_group_table.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user_table.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'group_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    op.drop_table('authenticator_table')
    op.drop_table('users_group_table')
    op.drop_table('user_table')
    op.drop_table('mfa_table')
    # ### end Alembic commands ###
